### ISSUE TITLE
Is it possible to change the Author?

### ISSUE THREAD

**Issue by andrepetinga** [tomolimo/mailbehaviours#4]
Hello.
Is it possible to change the author of the ticket to match the user from the ##from tag?

I asked this because when I use the tag, I'm still the ticket creator and when it is closed, I get the filter "Your tickets to close", so that I can validate the solution.

In my opinion this is wrong, because the requester is the one that should validade it.

**Comment by tomolimo** [comment]
Hello @andrepetinga 

Tell me: who is the real author? Answer: You and not the initial sender !
That's why the sender becomes the author (the writer) of the ticket

The validation of the solution is another issue, and is an issue of the GLPI core... If you create the ticket for someone else are you going to set the author as being the requester? If yes, then that's wrong, the requester was not the author, but you were! If you set the author equal to requester, then your ticket will not reflect reality...

This validation issue in GLPI core: we have the same issue in my company, with all the service desk people who are creating tickets for requesters....

Regards,
Tomolimo

**Comment by andrepetinga** [comment]
Yes, I understand I'm the author, but in my opinion, I'm the author because the original requester made a mistake of sending me an email instead of sending it to the support email.
And yes, if I create an email manually, I change the author to the requester :)
See this: the requester comes to the office asking for support, so I create a manual ticket in his name, and change the author to his email, because the ticket is not mine.

**Comment by tomolimo** [comment]
Hello @andrepetinga 

I believe that doing like you explained is not really ITIL compliant...

The author (or writer) field is not to tell that ticket is yours, but to tell who has created the ticket. And if the user is calling you, then you are the ticket writer but of course the ticket is not yours, you are the service desk agent who created the ticket, that's all!
The requester field is to tell to whom belong the ticket (incident or request)

It must work this way!

Thank you
Regards,
Tomolimo

**Comment by andrepetinga** [comment]
Ok. I understand your point of view 👍 
But our technicians don't like to see the option to validate the solution, because it just doesn't make sense. But, like you have mentioned, that is the GLPI core.
Thanks.
